<?php
/**
 * VehicleType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Exatia\GraphhopperRouteOptimizationClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Exatia\GraphhopperRouteOptimizationClient\Model;

use \ArrayAccess;

/**
 * VehicleType Class Doc Comment
 *
 * @category    Class
 * @package     Exatia\GraphhopperRouteOptimizationClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VehicleType implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'VehicleType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'type_id' => 'string',
        'profile' => 'string',
        'capacity' => 'int[]',
        'min_activities' => 'int',
        'speed_factor' => 'double',
        'service_time_factor' => 'double',
        'cost_fixed' => 'double',
        'cost_distance' => 'double',
        'cost_time' => 'double',
        'cost_service' => 'double',
        'cost_wait' => 'double',
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'type_id' => 'type_id',
        'profile' => 'profile',
        'capacity' => 'capacity',
        'min_activities' => 'min_activities',
        'speed_factor' => 'speed_factor',
        'service_time_factor' => 'service_time_factor',
        'cost_fixed' => 'cost_fixed',
        'cost_distance' => 'cost_distance',
        'cost_time' => 'cost_time',
        'cost_service' => 'cost_service',
        'cost_wait' => 'cost_wait',
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'type_id' => 'setTypeId',
        'profile' => 'setProfile',
        'capacity' => 'setCapacity',
        'min_activities' => 'setMinActivities',
        'speed_factor' => 'setSpeedFactor',
        'service_time_factor' => 'setServiceTimeFactor',
        'cost_fixed' => 'setCostFixed',
        'cost_distance' => 'setCostDistance',
        'cost_time' => 'setCostTime',
        'cost_service' => 'setCostService',
        'cost_wait' => 'setCostWait',
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'type_id' => 'getTypeId',
        'profile' => 'getProfile',
        'capacity' => 'getCapacity',
        'min_activities' => 'getMinActivities',
        'speed_factor' => 'getSpeedFactor',
        'service_time_factor' => 'getServiceTimeFactor',
        'cost_fixed' => 'getCostFixed',
        'cost_distance' => 'getCostDistance',
        'cost_time' => 'getCostTime',
        'cost_service' => 'getCostService',
        'cost_wait' => 'getCostWait',
    );

    public static function getters()
    {
        return self::$getters;
    }

    const PROFILE_CAR = 'car';
    const PROFILE_BIKE = 'bike';
    const PROFILE_FOOT = 'foot';
    const PROFILE_MTB = 'mtb';
    const PROFILE_MOTORCYCLE = 'motorcycle';
    const PROFILE_RACINGBIKE = 'racingbike';
    const PROFILE_TRUCK = 'truck';
    const PROFILE_SMALL_TRUCK = 'small_truck';
    const PROFILE_BUS = 'bus';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getProfileAllowableValues()
    {
        return [
            self::PROFILE_CAR,
            self::PROFILE_BIKE,
            self::PROFILE_FOOT,
            self::PROFILE_MTB,
            self::PROFILE_MOTORCYCLE,
            self::PROFILE_RACINGBIKE,
            self::PROFILE_TRUCK,
            self::PROFILE_SMALL_TRUCK,
            self::PROFILE_BUS,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type_id'] = isset($data['type_id']) ? $data['type_id'] : null;
        $this->container['profile'] = isset($data['profile']) ? $data['profile'] : null;
        $this->container['capacity'] = isset($data['capacity']) ? $data['capacity'] : null;
        $this->container['min_activities'] = isset($data['min_activities']) ? $data['min_activities'] : null;
        $this->container['speed_factor'] = isset($data['speed_factor']) ? $data['speed_factor'] : null;
        $this->container['service_time_factor'] = isset($data['service_time_factor']) ? $data['service_time_factor'] : null;
        $this->container['cost_fixed'] = isset($data['cost_fixed']) ? $data['cost_fixed'] : null;
        $this->container['cost_distance'] = isset($data['cost_distance']) ? $data['cost_distance'] : null;
        $this->container['cost_time'] = isset($data['cost_time']) ? $data['cost_time'] : null;
        $this->container['cost_service'] = isset($data['cost_service']) ? $data['cost_service'] : null;
        $this->container['cost_wait'] = isset($data['cost_wait']) ? $data['cost_wait'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("car", "bike", "foot", "mtb", "motorcycle", "racingbike", "truck", "small_truck", "bus");
        if (!in_array($this->container['profile'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'profile', must be one of #{allowed_values}.";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("car", "bike", "foot", "mtb", "motorcycle", "racingbike", "truck", "small_truck", "bus");
        if (!in_array($this->container['profile'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets type_id
     * @return string
     */
    public function getTypeId()
    {
        return $this->container['type_id'];
    }

    /**
     * Sets type_id
     * @param string $type_id Unique identifier for the vehicle type
     * @return $this
     */
    public function setTypeId($type_id)
    {
        $this->container['type_id'] = $type_id;

        return $this;
    }

    /**
     * Gets profile
     * @return string
     */
    public function getProfile()
    {
        return $this->container['profile'];
    }

    /**
     * Sets profile
     * @param string $profile Profile of vehicle type
     * @return $this
     */
    public function setProfile($profile)
    {
        $allowed_values = array('car', 'bike', 'foot', 'mtb', 'motorcycle', 'racingbike', 'truck', 'small_truck', 'bus');
        if (!in_array($profile, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'profile', must be one of 'car', 'bike', 'foot', 'mtb', 'motorcycle', 'racingbike', 'truck', 'small_truck', 'bus'");
        }
        $this->container['profile'] = $profile;

        return $this;
    }

    /**
     * Gets capacity
     * @return int[]
     */
    public function getCapacity()
    {
        return $this->container['capacity'];
    }

    /**
     * Sets capacity
     * @param int[] $capacity array of capacity dimensions
     * @return $this
     */
    public function setCapacity($capacity)
    {
        $this->container['capacity'] = $capacity;

        return $this;
    }

    /**
     * Gets minimun activities
     * @return int
     */
    public function getMinActivities()
    {
        return $this->container['min_activities'];
    }

    /**
     * Sets minimun activities
     * @param int $minActivities minimun activities
     * @return $this
     */
    public function setMinActivities($minActivities)
    {
        $this->container['min_activities'] = $minActivities;

        return $this;
    }

    /**
     * Gets speed_factor
     * @return double
     */
    public function getSpeedFactor()
    {
        return $this->container['speed_factor'];
    }

    /**
     * Sets speed_factor
     * @param double $speed_factor speed_factor of vehicle type
     * @return $this
     */
    public function setSpeedFactor($speed_factor)
    {
        $this->container['speed_factor'] = $speed_factor;

        return $this;
    }

    /**
     * Gets service_time_factor
     * @return double
     */
    public function getServiceTimeFactor()
    {
        return $this->container['service_time_factor'];
    }

    /**
     * Sets service_time_factor
     * @param double $service_time_factor service time factor of vehicle type
     * @return $this
     */
    public function setServiceTimeFactor($service_time_factor)
    {
        $this->container['service_time_factor'] = $service_time_factor;

        return $this;
    }

    /**
     * Gets cost_fixed
     * @return double
     */
    public function getCostFixed()
    {
        return $this->container['cost_fixed'];
    }

    /**
     * Sets cost_fixed
     * @param double $cost_fixed cost fixed of vehicle type
     * @return $this
     */
    public function setCostFixed($cost_fixed)
    {
        $this->container['cost_fixed'] = $cost_fixed;

        return $this;
    }

    /**
     * Gets cost_distance
     * @return double
     */
    public function getCostDistance()
    {
        return $this->container['cost_distance'];
    }

    /**
     * Sets cost_distance
     * @param double $cost_distance cost distance of vehicle type
     * @return $this
     */
    public function setCostDistance($cost_distance)
    {
        $this->container['cost_distance'] = $cost_distance;

        return $this;
    }

    /**
     * Gets cost_time
     * @return double
     */
    public function getCostTime()
    {
        return $this->container['cost_time'];
    }

    /**
     * Sets cost_time
     * @param double $cost_time cost time of vehicle type
     * @return $this
     */
    public function setCostTime($cost_time)
    {
        $this->container['cost_time'] = $cost_time;

        return $this;
    }

    /**
     * Gets cost_service
     * @return double
     */
    public function getCostService()
    {
        return $this->container['cost_service'];
    }

    /**
     * Sets cost_service
     * @param double $cost_service cost service of vehicle type
     * @return $this
     */
    public function setCostService($cost_service)
    {
        $this->container['cost_service'] = $cost_service;

        return $this;
    }

    /**
     * Gets cost_wait
     * @return double
     */
    public function getCostWait()
    {
        return $this->container['cost_wait'];
    }

    /**
     * Sets cost_wait
     * @param double $cost_wait cost wait of vehicle type
     * @return $this
     */
    public function setCostWait($cost_wait)
    {
        $this->container['cost_wait'] = $cost_wait;

        return $this;
    }


    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset): mixed
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Exatia\GraphhopperRouteOptimizationClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Exatia\GraphhopperRouteOptimizationClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}
